version: '3.8'
services:
  db:
    image: postgres:15-alpine3.20
    restart: always
    environment:
      - POSTGRES_DB=nestjs-auth-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ../nestjs-auth-db:/var/lib/postgresql/data
